# Generated by Django 4.1.5 on 2023-01-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=50)),
                ('stadium', models.CharField(max_length=50)),
                ('honors', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
